server:
  port: 8761

spring:
  application:
    name: eurekaServer

eureka:
  server:
    eviction-interval-timer-in-ms: 120000 # ??? ?? ??
    renewal-percent-threshold: 0.85       # ?? ?? ?? ???
    renewal-threshold-update-interval-ms: 60000
  client:
    register-with-eureka: false # ??? ???? ??
    fetch-registry : false # ?? ?????? ???? ??