server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: stock-batch
          uri: lb://stock-batch
          predicates:
            - name: Path
              args:
                pattern: /batch/**
        - id: ms2
          uri: http://localhost:8082
          predicates:
            - name: Path
              args:
                pattern: /ms2/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry : true
    service-url:
      defaultZone-url: http://localhost:9000/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway