server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:file:.env[.properties]"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: gateway,health,info

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: stock-corp
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/corp/**
          filters:
            - StripPrefix=3
        - id: stock-finance
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/finance/**
          filters:
            - StripPrefix=3
        - id: stock-price
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/stock/**
          filters:
            - StripPrefix=3
        - id: stock-strategy
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/strategy/**
          filters:
            - StripPrefix=3

eureka:
  client:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: stock-corp
          uri: lb://STOCK-CORP
          predicates:
            - Path=/api/v1/corp/**
          filters:
            - StripPrefix=3
        - id: stock-finance
          uri: lb://STOCK-FINANCE
          predicates:
            - Path=/api/v1/finance/**
          filters:
            - StripPrefix=3
        - id: stock-price
          uri: lb://STOCK-PRICE
          predicates:
            - Path=/api/v1/stock/**
          filters:
            - StripPrefix=3
        - id: stock-strategy
          uri: lb://STOCK-STRATEGY
          predicates:
            - Path=/api/v1/strategy/**
          filters:
            - StripPrefix=3

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry : true
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:1234}@stock-discovery:8761/eureka
