server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:file:.env[.properties]"

  cloud:
    gateway:
      routes:
        - id: stock-corp
          uri: lb://stock-corp
          predicates:
            - Path=/api/v1/corp/**
        - id: stock-finance
          uri: lb://stock-finance
          predicates:
            - Path=/api/v1/finance/**
        - id: stock-stock
          uri: lb://stock-stock
          predicates:
            - Path=/api/v1/stock/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry : true
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:1234}@localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
