spring:
  h2:
    console:
      enabled: false
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  config:
    import: "optional:configserver:"   #configserver 무시 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-h2.sql
  datasource-meta:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:1521/./meta-db;MODE=MariaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
  datasource-data:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost:1521/./data-db;MODE=MariaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:

data-go:
  service-key: ${data-go.service-key}

dart:
  api-key: ${dart.api-key}
