spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  config:
    import: "optional:configserver:"   #configserver 무시 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/meta_db?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "${MYSQL_PASSWORD:root1234}"
  datasource-data:
    ddl-auto: update
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/data_db?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "${MYSQL_PASSWORD:root1234}"

data-go:
  service-key: ${data-go.service-key}

dart:
  api-key: ${dart.api-key}
